//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtobus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avtobus()
        {
            this.Perevozka = new HashSet<Perevozka>();
        }
    
        public int ID_Avtobus { get; set; }
        public string Nomer { get; set; }
        public string Model { get; set; }
        public string Nomernoi_Znak { get; set; }
        public int kolbo_Mest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perevozka> Perevozka { get; set; }
    }
}
