//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marshrut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marshrut()
        {
            this.Perevozka = new HashSet<Perevozka>();
        }
    
        public int ID_Marshrut { get; set; }
        public string Nomer_Marshruta { get; set; }
        public string Punkt_naznachenia { get; set; }
        public string Raion { get; set; }
        public string Oblast { get; set; }
        public int Rasstoyanie { get; set; }
        public int Ves { get; set; }
        public System.DateTime Vremia_Otpravki { get; set; }
        public System.DateTime Vremia_Pribitiya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perevozka> Perevozka { get; set; }
    }
}
