//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voditel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voditel()
        {
            this.Perevozka = new HashSet<Perevozka>();
        }
    
        public int ID_Voditel { get; set; }
        public string F_I_O { get; set; }
        public System.DateTime Data_Rojdenia { get; set; }
        public string Passpot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perevozka> Perevozka { get; set; }
    }
}
